### PR TITLE
Fixed issue with _eachLimit continuing to run after error

### PR DESCRIPTION
**Pull request by bao987654321**
Solved issue described in https://github.com/caolan/async/issues/649

### CODE REVIEW

**Comment by aearly** [comment]
Can you pull from upstream and resolve the conflicts?  Also, can you write a test for the failing behavior this fixes?

**Comment by bao987654321** [comment]
Will do.

**Comment by bao987654321** [comment]
I've added the tests for this.

**Comment by aearly** [comment]
Thanks a lot!

**Pull request merged**
