### PR TITLE
chore: remove Azure DevOps CI

### PR DESCRIPTION
**Pull request by nschonni**
Cleaned up JUnit reporters that were used for test uploads there too

### CODE REVIEW

**Comment by aearly** [comment]
Thanks for this.  Azure CI was offered to this project promotionally, but GitHub Actions is now way more convenient.  Can you rebase this PR?

**Comment by nschonni** [comment]
@aearly gave it a rebase

**Comment by aearly** [comment]
BTW, I want to thank you for your contributions to this project.  A lot of this stuff has been growing weeds, and it's nice to be on a more modern set of tools.

**Comment by nschonni** [comment]
No worries. I was poking around the Makefile after to see what might need to be done to integrate it into the CI too.
Was thinking it might make sense to migrate it into package.json scripts, but haven't wrapped my head around it yet :)
The Mocha upgrade also needs to migrate to Babel 7, but I'm not confident I wouldn't break anything before getting that full build to diff against

**Comment by aearly** [comment]
The Makefile is pretty load bearing, we're relying on a lot of Make functionality that is difficult to replicate in other tools.

One thing that is pretty out of date is the package publishing workflow.

**Comment by nschonni** [comment]
Semantic release might be something to look at https://github.com/htmlhint/HTMLHint/blob/200e2e522762e4184abaa10bcf77367e20c2f410/.github/workflows/production.yml#L91

**Pull request merged**
