### PR TITLE
Add detectLimit

### PR DESCRIPTION
**Pull request by markyen**
This function is already in the documentation but was not in the implementation.

### CODE REVIEW

**Comment by aearly** [comment]
:+1:  good catch

**Comment by megawac** [comment]
Probably worth a patch release

Also yeah, I think it was going to get added in #847 :p

**Comment by aearly** [comment]
Ah, forgot about that.  This can fill in until we're ready for that PR.

**Comment by megawac** [comment]
Definitely, and adds tests. Thanks @markyen!

**Pull request merged**
