### PR TITLE
Implement eachOf via keyIterator

### PR DESCRIPTION
**Pull request by megawac**
The main advantage of this is if we plan further refactors (#839, #847)

Can't believe this worked in one try (:D)

### CODE REVIEW

**Comment by aearly** [comment]
Cool. I thought this method already used the key iterator...

**Comment by megawac** [comment]
Only one more place uses `_objectEach` now too

**Comment by charlierudolph** [comment]
This was editing dist exclusively. I think this needs to be reverted and applied to lib

**Comment by megawac** [comment]
Ha, whoops, want to do that @charlierudolph

**Pull request merged**
