### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by cmswalker**
just a safety note for those that have yet to upgrade to 2.0.0

### CODE REVIEW

**Comment by aearly** [comment]
I'm not sure how much hand-holding to do here.  There's a note at the top of the readme, as well as a changelog.

**Comment by cmswalker** [comment]
ah, missed the note

**Comment by aearly** [comment]
In all fairness, I just added it a few hours ago. :new_moon_with_face:

**Comment by megawac** [comment]
Do we want to bold, highlight, underline and 90 pt font that note?

**Comment by aearly** [comment]
I'll just continue to close issues as they arise.  It heightens a sense of productivity. :smiley: :

**Pull request closed without merging**
