### PR TITLE
Code changes to standardize style

### PR DESCRIPTION
**Pull request by rheh**
Trivial changes to style to standardize style of function definitions, if statement braces etc.  Style implemented follows that used in the majority of the code.

### CODE REVIEW

**Comment by aearly** [comment]
I'd prefer to remain un-opinionated about this kind of thing.  All we use JSCS for is to make indentation consistent, because that really affects readability.  IMO, stuff like this doesn't really inhibit readability or maintainability.

**Comment by rheh** [comment]
Yeah, I can see your point - a few years back I felt the same.  I feel having a coding standard and publishing one sets good intentions and can encourage those of a caution nature to contribute - which from my own experience can be a little daunting.

**Comment by dougmoscrop** [comment]
If you're going to adopt a style, having an .editorconfig would be helpful. (JSCS also does an 'auto-fix' now, right?)

**Comment by megawac** [comment]
I was going to do this originally in https://github.com/caolan/async/pull/837 along with consistent brace&parenthesis use, but dropped it after resistance. +0 from me

**Comment by megawac** [comment]
If we are going to accept this I think you should set the jscsrc config to use a stricter set of presets (airbnb or google for instance)

**Comment by aearly** [comment]
If we do this, I think we should set up ghooks to run any linters/style-checkers on commit.  Nothing is more annoying when a PR fails CI due to style nits.

**Comment by hstonge** [comment]
+1 for .editorconfig file

**Pull request closed without merging**
