### PR TITLE
Add reflect function wrapper to allow always passing iterations

### PR DESCRIPTION
**Pull request by jtwebman**
Add reflect that wraps a function with a always passing callback and a object with error or value property set.

This is one way to solve issue #942.

### CODE REVIEW

**Comment by aearly** [comment]
:+1:   @megawac What do you think?

We're probably going to hold of on merging this until #996 is complete, though,

**Comment by jtwebman** [comment]
Should I add in a reflectAll helper as well?

**Comment by aearly** [comment]
Sure.  It's pretty simple though -- `async.reflectAll(tasks)` vs. `tasks.map(async.reflectAll)`.

**Comment by jtwebman** [comment]
Added reflectAll as well as debased off master. I'll wait for the other PR to be merged in and then refactor for that.

**Comment by aearly** [comment]
You should be good to go for your refactoring. :+1:

**Comment by aearly** [comment]
@jtwebman Any update?  This is the last change for the 2.0 release.

**Comment by jtwebman** [comment]
@aearly I can get this in tomorrow for you. Been moving the family to Portland the last two weeks.

**Comment by aearly** [comment]
Ah, no rush.  Worst case, we save it for 2.1.

**Comment by aearly** [comment]
@jtwebman How are things going? Should we save this for a later release?

**Comment by jtwebman** [comment]
Sorry about the delay, was down and out sick.

**Comment by jtwebman** [comment]
I an going to close this PR as I opened a new one for this as the files changed and merged freaked out. https://github.com/caolan/async/pull/1095

**Pull request closed without merging**
