### PR TITLE
filter, reject, detect, some, every with error

### LINKED ISSUE #118: Allow every and filter callbacks to receive errors as first argument
The fact that the callbacks for the every and filter functions don't accept an error object can be restrictive in some situations. For example when you do I/O operations in the iterator, you might want to differentiate between an I/O error and a result that got filtered in the final callback. Right now the API does not allow you to differentiate between the two cases.

I understand that these functions were designed this way because of certain nodejs API (path.exists), but maybe we could have alternative versions of these functions (everyWithError, filterWithError) or have smart behavior that can handle both cases. The latter solution would consider the first argument of the callback to be an error only if two arguments were passed. That error would be passed to the final callback as the first argument as well, as happens with the other functions.

I might try to write a patch for the last solution sometime soon.

### PR DESCRIPTION
**Pull request by charlierudolph**
@aearly 

fixes #118

### CODE REVIEW

**Comment by aearly** [comment]
Thanks for this.  It's going to be on hold until we're putting together async 2.0, though.

**Comment by charlierudolph** [comment]
Sounds good. Let me know if this ever needs any updates

**Comment by charlierudolph** [comment]
Updated this to include detect and fixes to the README.md

**Comment by megawac** [comment]
Definitely :+1: on this

**Comment by davidlondono** [comment]
+1

**Comment by charlierudolph** [comment]
@aearly @megawac any update? I'd like to see this either merged into master or a dedicated 2.0 branch instead of leaving this sitting around.

**Comment by megawac** [comment]
:+1: I want to get one more 1.4.3 release out before we start a 2.0 branch tho (cause itll be a pain to keep rebasing the two)

**Comment by aearly** [comment]
Sorry, been to busy recently to have free cycles for async :(

**Comment by charlierudolph** [comment]
Why do you even need a 2.0 branch? As long as you are following semantic versioning whats wrong with introducing a breaking change?

**Comment by aearly** [comment]
It's nicer for people downstream to release a batch of breaking changes all at once, rather than one at a time.  It's less work for people to have to check for breaking changes in their code at fewer times throughout the year.

**Comment by charlierudolph** [comment]
@aearly @megawac any update this on this?

**Comment by megawac** [comment]
Still definitely :+1: but we're in the process of moving into a modular setup for a major version bump (#996, https://github.com/caolan/async/tree/modularization). If you want to reopen against that branch we'll get it in quickly, otherwise we'll pull in when where ready to merge that branch with master

**Comment by aearly** [comment]
Closed via #1028!

**Pull request closed without merging**
