### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by tmacro**
`unshirtAsync` => `unshiftAsync`

### CODE REVIEW

**Review by aearly — CHANGES_REQUESTED** [review]
Can you update the source for these docs in lib/queue.js?

**Comment by tmacro** [comment]
sure thing

**Comment by tmacro** [comment]
@aearly should I remove the fix in `docs/v3` as upon closer inspection it looks like they're generate from the source?

**Comment by aearly** [comment]
You can run  `make doc` and it will regenerate.

**Comment by aearly** [comment]
Re-open this when you fix `lib/queue.js`

**Pull request closed without merging**
