### PR TITLE
Add anyway version of map and parallel

### PR DESCRIPTION
**Pull request by allevo**
Use mapAnyway or parallelAnyway for doing something in parallel but if some tasks fail, the others will be executed anyway. In the final callback, the first parameter is valued with all errors. For mapAnyway, the second parameter with all mapped object.
Add main test for parallelAnyway and mapAnyway.

### CODE REVIEW

**Comment by aearly** [comment]
I like this idea, but I dislike the global `collect` and `uncollect` states.  Closing this in #349.  We'll think up a general solution.

**Comment by aearly** [comment]
Nevermind, got PRs  mixed up.

**Comment by kmgilbert100** [comment]
+1

**Comment by gocoffeecup** [comment]
+1

**Comment by kmgilbert100** [comment]
Why hasn't this been added yet?

**Comment by allevo** [comment]
Because @caolan hasn't decided the names yet. As soon as possible, I'll resolve the conflict and repush the PR

**Comment by aearly** [comment]
I realized that this breaks one of `map`'s guarantees -- that the results returned in the same order as their inputs in the original array.  If half your tasks callback an error, you'll get a results array that is half the  size of the original array.  It also is a bit of a convention break to return an array of errors (rather than a single `Error` object) as the first arg to a callback.

We're going to go back to the drawing board with #942

**Pull request closed without merging**
