### PR TITLE
Added exception handling to async waterfall method.

### PR DESCRIPTION
**Pull request by diogogmt**
Adding exception handling for async.waterfall

### CODE REVIEW

**Comment by coderbuzz** [comment]
Sorry to bumb it, I'm looking this feature too. +1
I'm too lazy writing try {} catch on each function :p

**Comment by wookieb** [comment]
@caolan @aearly What need to happen to convince you to introduce try/catch error handling for async?

1) Handling nested async errors
I think it's clear it's impossible to do. The same as it's impossible to do for promises.
But the simplest possible case is still a big improvement. Wrapping all possible workers with try/catch (or having helper for that) introduce a lot of boilerplate. As programmers we have to be productive and boilerplate is very counter productive. In that case is also very error-prone.

2) Such huge change requires major version change
Let's do it then instead forcing 1 000 000 + of programmers to introduce a lot of boilerplate because we don't want to do it.

3) Performance hit
Do we have exact measures on that? I'm happy to see them if possible.
If we don't have them I can do it. Just let me know.

4) Async functions should pass errors with callbacks
That's right. Promises should be always resolved or rejected, yet auto rejection on throw has been added to the spec of Promises/A+. Design ideology <<< Reality.

**Comment by aearly** [comment]
Automatically wrapping everything in try/catch internally is actually impossible to do properly.  You either end up catching errors later in the callback chain after a successful task, or you end up having to introduce a deferral for each async step (as promises do).  We just eliminated all unnecessary deferrals throughout Async, so we're not going to add them back in.

**Comment by wookieb** [comment]
Thanks for your quick answer @aearly 

"You either end up catching errors later in the callback chain after a successful task"
Could you please provide some example?

**Comment by aearly** [comment]
```js
function asyncMethod(args, iteratee, callback) {
  try {
    iteratee(args, callback);
  } catch (err) {
    callback(err);
  }
}

asyncMethod(args, asyncFn, function (err, res) {
  throw new Error("in callback"); <-- this error will be caught above
})

```

**Pull request closed without merging**
