### PR TITLE
Support function timeout via async.timeout wrapper

### PR DESCRIPTION
**Pull request by ajfranzoia**
Implements timeout feature discussed in #1007. 
Follows @aearly advice on using a wrapper around the asynchronous functions. I changed the function arguments' order to match ```setTimeout``` signature.
If there are any mistakes or things that need modification, just let me know.
I can add the readme info if this looks good.

### CODE REVIEW

**Comment by aearly** [comment]
I'm still :100: on this, but master has changed significantly.  Can you re-do the work?  It also would be nice if you added a `mocha_test` too.

**Comment by ajfranzoia** [comment]
Sure, I'll redo this and add a mocha test as well :+1:

**Comment by ajfranzoia** [comment]
Re-did this to support the new master and added a mocha test. I did some refactoring as well to the original code to make it clearer.

**Comment by tjwudi** [comment]
This is a nice feature! Probably add some docs to it? :)

**Comment by ajfranzoia** [comment]
Added docs via #1051.

**Pull request merged**
